run:
  deadline: 5m
  skip-dirs:
    - go/pkg/mod
linters:
  enable:
    - vet
    - staticcheck
    - errcheck
    - gofmt
    - goimports
    - whitespace
    - unused
    - ineffassign
    - prealloc
    - stylecheck
    - goconst
    - gosimple
    - misspell
#    - gosec
  enable-all: false
  disable-all: true
  fast: false
linters-settings:
  goimports:
    local-prefixes: github.com/futuretea/harvester-auto
