---
fail_fast: false
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.30.0
    hooks:
      - id: yamllint
        args:
          - --config-file
          - .yamllint.yaml
  - repo: https://github.com/ansible-community/ansible-lint
    rev: v6.16.0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        entry: ansible-lint . --force-color -v -p
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.22
    hooks:
      - id: terraform-fmt
      - id: tflint
      - id: shellcheck
      - id: gofmt
      - id: golangci-lint
